@{
#
# Module manifest for module 'WSUSResponder'
#
# Generated by: Expert PowerShell AD
#
# Generated on: 27/10/2025
#

# Le fichier .psm1 principal
RootModule = 'WSUSResponder.psm1'

# Version number of this module.
ModuleVersion = '1.0.1' # Incrémenté pour refléter les améliorations

# GUID of this module
GUID = 'e9e8b7e0-1c7c-4a9f-8a2a-7f6e8d1c9f0d'

# Author of this module
Author = 'Admin'

# Company or vendor of this module
CompanyName = 'IT Operations'

# Copyright statement for this module
Copyright = '(c) 2025 IT Operations. All rights reserved.'

# Description of the functionality provided by this module.
Description = "Module de réponse à l'incident CVE-2025-59287 (WSUS). Permet de scanner, d'appliquer et de retirer le workaround de pare-feu."

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module
FunctionsToExport = @(
    'Get-WSUSCveStatus',
    'Set-WSUSCveWorkaround',
    'Remove-WSUSCveWorkaround',
    'Export-WSUSCveReport'
)

# List of modules required by this module
RequiredModules = @(
    @{ ModuleName = 'ActiveDirectory'; ModuleVersion = '1.0.0.0' },
    @{ ModuleName = 'ImportExcel'; ModuleVersion = '7.0.0' } # Version 7+ est courante
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# Private data to pass to the module.
PrivateData = @{

    PSData = @{
        # Tags associated with this module, for example
        Tags = @('WSUS', 'CVE', 'Security', 'Responder', 'IncidentResponse')
    }
}

}

